### ISSUE TITLE
extend goldenmaster with a module that starts with capital letter (and interfaces)

### ISSUE THREAD

**Issue by dorotaphanSiili** [apigear-io/template-qtcpp#30]
### Description

extend goldenmaster with a module that starts with capital letter (and interfaces)

**Comment by dorotaphanSiili** [comment]
already added with fix: fix for not standard name convention https://github.com/apigear-io/template-qtcpp/commit/ef02ddc88590c97c290820ba872a5eef28f7945f

**Comment by dorotaphanSiili** [comment]
partialy fixed - interface already added here https://github.com/apigear-io/template-qtcpp/commit/ef02ddc88590c97c290820ba872a5eef28f7945f

**Comment by w4bremer** [comment]
Will be fixed with https://github.com/apigear-io/cli/issues/122
