### ISSUE TITLE
Discuss: should we remove generating QDataStream operators

### ISSUE THREAD

**Issue by dorotaphanSiili** [apigear-io/template-qtcpp#32]
### Description

It is used for serialization to QDataStream, we use nlohmann::json for that.
Is this unnecessary infrastructure for "convenience"? Or it should stay?
Cons: requires maintenance, needs to be read - makes the file longer in most cases unnecessarily.
Pro: if the user wants to use that, it is already there, no need changing own template (which then need to be maintained) 

connected to https://github.com/apigear-io/template-qtcpp/issues/33

**Comment by w4bremer** [comment]
After discussion, leave like is for now.
